forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-git'
mod 'puppetlabs-apt'
mod 'jbussdieker-carbon'
mod 'jbussdieker-whisper'
mod 'jbussdieker-graphite_web', '>= 0.0.8'
mod 'puppetlabs-rabbitmq'
mod 'pdxcat-collectd'
mod 'zooz-uwsgi'
mod 'jfryman-nginx'
